name: Update Changelog
description: |
  Uses AI to update the changelog based on the commits from the last release.  Recommended to run with a timeout (say 8
  minutes) to give enough time for the AI to work.
inputs:
  agent-token:
    description: "Token to use with AI agent."
    required: true
  github-token:
    description: "Token to use with GitHub API."
    required: true
  release-version:
    description: "Version of the release."
    required: true
runs:
  using: composite
  steps:
    - name: Update Documentation
      uses: LimeMojito/oss-maven-standards/.github/actions/invoke-agent@master
      with:
        agent-token: ${{ inputs.agent-token }}
        github-token: ${{ inputs.github-token }}
        prompt: |
          Using the version number ${{ inputs.release-version }}, update ${{ github.workspace }}/CHANGELOG.md
          to summarize the git commits since the last release tag, where the last release tag is the top most heading of 
          changes in the current CHANGELOG.md.
          
          If there is no previous CHANGELOG.md file, create one at ${{ github.workspace }}/CHANGELOG.md. Create a new
          heading for the version number ${{ inputs.release-version }}.  Underneath it summarize the modules
          in this project that have been added with a description of the changes.

          In the summary that has been added perform the following;
            - summarize the modules in this project that have been added with a description of the changes.
            - where there are multiple summary items containing related issues keys (#XXXXX or AAA-XXX format) group 
              these items and summarize into one description of the changes per issue.
            - where there are multiple summary items referring to version updates or pom updates, replace them with a 
              single item that is "Updated versions and security patches."
            - remove all summary items that contain any of the following
              - [maven-release-plugin]
              - [Release]
              - [Development]
              - [artifactory-release]
              - updating poms
            - Remove any summary items that refer to merges.

          Add a heading of Latest Changes with content as a link to the CHANGELOG.md in the Readme.md file if it 
          doesn't already exist.

          Do not commit these changes or make a pull request, leave the files edited in place.

    - name: Commit Documentation updates
      shell: bash
      run: |
        echo "Committing Documentation updates for ${{ inputs.release-version }}."
        git add CHANGELOG.md
        git commit -S -m "Updated Documentation for release build ${{ inputs.release-version }}."
