name: Invoke Agent
description: |
  Invoke AI Agent with a specific prompt.  Note this action is a "raw" Junie invoke and does not support
  the github workflow version that generates PRs, responds to issues and chats etc.  This action will not run unless the 
  caller is a member of the developers team.

inputs:
  prompt:
    description: Markdown prompt to invoke agent with.
    required: true
  agent-token:
    description: The api key to use agent with
    required: true
  github-token:
    description: The github token to use for github requests by this action.
    required: true

runs:
  using: composite
  steps:
    - name: allowed-user-check
      id: auth_check
      uses: GuillaumeFalourd/github-team-members@v1
      with:
        org_slug: LimeMojito
        team_slug: developers
        token: ${{ inputs.github-token }}

    - if: steps.auth_check.outputs.actor-belongs-team == 'true'
      run: echo "${{ github.actor }} belongs to Team"
      shell: bash

    - if: steps.auth_check.outputs.actor-belongs-team == 'false'
      run: echo "${{ github.actor }} doesn't belong to Team"
      shell: bash

    - name: Install Junie CLI Windows
      if: runner.os == 'Windows' && steps.auth_check.outputs.actor-belongs-team == 'true'
      shell: pwsh
      run: |
        if (!(Get-Command junie -ErrorAction SilentlyContinue)) {
          Write-Host "Junie CLI not found. Installing..."
          iex (irm 'https://junie.jetbrains.com/install.ps1')
        
          $junieBin = Join-Path $env:USERPROFILE '.local\bin'
          "$junieBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          $env:PATH = "$junieBin;$env:PATH"
          
          Write-Host "Junie path added to workflow PATH."
          Get-Command junie | Out-String | Write-Host
        }

    - name: Invoke Junie Windows
      if: runner.os == 'Windows' && steps.auth_check.outputs.actor-belongs-team == 'true'
      shell: pwsh
      run: |
        $env:JUNIE_API_KEY='${{ inputs.agent-token }}'
        $prompt = @'
            ${{inputs.prompt}}
        '@
        $prompt | junie

    - name: Install Junie CLI Unix
      if: (runner.os == 'Linux' || runner.os == 'macOS') && steps.auth_check.outputs.actor-belongs-team == 'true'
      shell: bash
      run: |
        if ! command -v junie &> /dev/null
        then
          curl -fsSL https://junie.jetbrains.com/install.sh | bash
        fi

    - name: Invoke Junie Unix
      if: (runner.os == 'Linux' || runner.os == 'macOS') && steps.auth_check.outputs.actor-belongs-team == 'true'
      shell: bash
      run: |
        export JUNIE_API_KEY=${{ inputs.agent-token }}
        junie --skip-update-check --auth="${JUNIE_API_KEY}" << 'EOF'
        ${{ inputs.prompt }}
        EOF
