name: Invoke Agent
description: |
  Invoke AI Agent with a specific prompt.  Note this action is a "raw" Junie invoke and does not support
  the github workflow version that generates PRs, responds to issues and chats etc.

inputs:
  prompt:
    description: Markdown prompt to invoke agent with.
    required: true
  agent-token:
    description: The api key to use agent with
    required: true

runs:
  using: composite
  steps:
    - name: Install Junie CLI Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
          if (!(Get-Command junie -ErrorAction SilentlyContinue)) {
            echo "Junie CLI not found. Installing..."
            iex (irm 'https://junie.jetbrains.com/install.ps1')
          }

    - name: Install Junie CLI Unix
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        if ! command -v junie &> /dev/null
        then
          curl -fsSL https://junie.jetbrains.com/install.sh | bash
        fi

    - name: Invoke Junie
      shell: bash
      run: |
        export JUNIE_API_KEY=${{ inputs.agent-token }}
        junie --skip-update-check --auth="${JUNIE_API_KEY}" << 'EOF'
        ${{ inputs.prompt }}
        EOF
