description: "Performs a build and maven deployment similar to a maven release with commits."
inputs:
  code-signing-key-name:
    description: 'Code signing GPG key name'
    required: true
  code-signing-passphrase:
    description: 'Code signing GPG passphrase'
    required: true
  extra-mvn-options:
    description: 'Extra maven command line options'
    required: false
outputs:
  release-version:
    description: 'The release version'
    value: ${{ steps.git_release_version.outputs.build-version }}

runs:
  using: composite
  steps:
    - name: Calculate Release Version
      id: git_release_version
      uses: LimeMojito/oss-maven-standards/.github/actions/calculate-build-version@master

    - name: Perform Release Deployment
      shell: bash
      run: |
        echo -e "\n\nDeploying Release version ${{steps.git_release_version.outputs.build-version }}"
        # Needs to match github runner architecture.
        export DOCKER_DEFAULT_PLATFORM=linux/amd64
        export MAVEN_GPG_PASSPHRASE="${{ inputs.code-signing-passphrase }}"
        # deploy to OSSRH.
        mvn -B --color always --no-transfer-progress \
          versions:set -DnewVersion=${{steps.git_release_version.outputs.build-version}}
        mvn -B --color always --no-transfer-progress \
          -Dbuild.number=${{github.run_number}} \
          -Dgpg.keyname='${{inputs.code-signing-key-name}}' ${{ inputs.extra-mvn-options }} \
          -P release \
          deploy

    - name: Tag Release Version ${{steps.git_release_version.outputs.build-version }}
      shell: bash
      run: |
        echo -e "Tag release version\n\n"
        tagName="${{steps.git_release_version.outputs.build-version }}"
        echo "Tagging repository with [$tagName]"
        git tag -s $tagName -m "[Release] $tagName"

    - name: Revert version change to ${{steps.git_release_version.outputs.old-version}}
      shell: bash
      run: |
        mvn -B --color always --no-transfer-progress versions:set -DnewVersion=${{steps.git_release_version.outputs.old-version}}

    - name: Ensure No Git Changes Exist
      shell: bash
      run: |
          if ! git diff --quiet; then
            echo "❌ Error: Modified files detected!"
            git diff
            exit 1
          else
            echo "✅ Clean: No modified files found."
          fi
