description: "Performs a build and maven deployment similar to a maven release with commits pushed at the end."
inputs:
  code-signing-key-name:
    description: 'Code signing GPG key name'
    required: true
  code-signing-passphrase:
    description: 'Code signing GPG passphrase'
    required: true
  extra-mvn-options:
    description: 'Extra maven command line options'
    required: false
outputs:
  release-version:
    description: 'The release version'
    value: ${{ steps.git_release_version.outputs.build-version }}

runs:
  using: composite
  steps:
    - name: Maven Fast Build
      uses: LimeMojito/oss-maven-standards/.github/actions/maven-fast-build@master
      with:
        signing-passphrase: ${{ inputs.signing-passphrase }}
        code-signing-key-name: ${{ inputs.code-signing-key-name }}
        extra-mvn-options: ${{ inputs.extra-mvn-options }}

    - name: Calculate Release Version
      id: git_release_version
      uses: LimeMojito/oss-maven-standards/.github/actions/calculate-build-version@master

    - name: Perform Release Deployment
      shell: bash
      run: |
        echo -e "\n\nDeploying Release version ${{steps.git_release_version.outputs.build-version }}"
        # Needs to match github runner architecture.
        export DOCKER_DEFAULT_PLATFORM=linux/amd64
        export MAVEN_GPG_PASSPHRASE="${{ inputs.code-signing-passphrase }}"
        # deploy to OSSRH, extra options twice to make sure passed through to release.  Note escaped quotes to arguments property.
        mvn -B --color always --no-transfer-progress \
          -Dbuild.number=${{github.run_number}} \
          -Dgpg.keyname='${{inputs.code-signing-key-name}}' ${{ inputs.extra-mvn-options }} \
          -Darguments="-B --color always --no-transfer-progress -Dbuild.number=${{github.run_number}} -Dgpg.keyname=\"${{inputs.code-signing-key-name}}\" ${{ inputs.extra-mvn-options }}" \
          releaser:release

    - name: Tag Release Version
      shell: bash
      run: |
        echo -e "Tag release version\n\n"
        tagName="${{steps.git_release_version.outputs.build-version }}"
        echo "Tagging repository with [$tagName]"
        git tag -s $tagName -m "[Release] $tagName"        
        git push origin "$tagName" --quiet
        echo "lime-release-version=$tagName" >> "$GITHUB_OUTPUT"

    - name: Ensure No Git Changes Exist
        run: |
          if ! git diff --quiet; then
            echo "❌ Error: Modified files detected!"
            git diff
            exit 1
          else
            echo "✅ Clean: No modified files found."
          fi
