name: "Lime Environment Setup"
description: "Configures the build environment to work with Lime resources."
inputs:
  aws-region:
    description: 'AWS Region name'
    required: true
  role-to-assume:
    description: 'AWS Role ARN to run with'
    required: true
  signing-key:
    description: 'Code signing GPG key data'
    required: true

outputs:
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ github.repository_id }}-${{ github.run_id }}

    - name: Install Python dependencies and CDK
      run: |
        python -m pip install --upgrade pip
        # install your Python dependencies here
        npm install -g aws-cdk

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.signing-key }}

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.3.7
      with:
        key: docker-LimeMojito-OSS
