name: "Lime Environment Setup"
description: "Configures the build environment to work with Lime resources ( Java, AWS, Docker[ARM] )."
inputs:
  aws-region:
    description: 'AWS Region name'
    required: true
  role-to-assume:
    description: 'AWS Role ARN to run with'
    required: true
  code-signing-key:
    description: 'Code signing GPG key data'
    required: true
  code-signing-passphrase:
    description: 'Code signing GPG passphrase'
    required: true

runs:
  using: composite
  steps:
    - name: Lime Setup AWS
      uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup-aws@master
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        code-signing-key: ${{ inputs.code-signing-key }}
        code-signing-passphrase: ${{ inputs.code-signing-passphrase }}

    - uses: docker/setup-qemu-action@v3
      with:
        platforms: 'arm64'

    - uses: docker/setup-buildx-action@v3

    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-LimeMojito-OSS
