name: "Lime Environment Setup (Java)"
description: "Configures the build environment to work with Lime resources (Java, Maven)."
inputs:
  code-signing-key:
    description: 'Code signing GPG key data'
    required: true
  code-signing-passphrase:
    description: 'Code signing GPG passphrase'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        ssh-key: "${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}"

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'corretto'
        cache: 'maven'

    - name: Import GPG key for Jar signing
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.code-signing-key }}
        passphrase: ${{ inputs.code-signing-passphrase }}

    - name: Import GPG key for Build Commits
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.LIME_BUILD_AGENT_GIT_SIGNING_KEY }}
        git_committer_email: "build@limemojito.com"
        git_committer_name: "Lime Build Agent"
        git_user_signingkey: true
        git_push_gpgsign: false
        git_tag_gpgsign: true
        git_commit_gpgsign: true
        git_config_global: true
