name: "Lime Environment Setup (Java)"
description: |
  Checks out the codebase.
  Configures the build environment to work with Lime resources (Java, Maven).
inputs:
  code-signing-key:
    description: 'Code signing GPG key data'
    required: true
  code-signing-passphrase:
    description: 'Code signing GPG passphrase'
    required: true
  central-id:
    description: 'Central repository username'
    required: true
  central-key:
    description: 'Central repository password'
    required: true
  localstack-token:
    description: 'LocalStack access token'
    required: true
runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'corretto'
        cache: 'maven'

    - name: Configure OSS Maven Settings.xml
      id: maven_setup
      shell: bash
      run: |
        localSettings=~/.m2/settings.xml
        cat > "$localSettings" <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <settings>
            <servers>
             <server>
               <id>central</id>
               <username>${{ inputs.central-id }}</username>
               <password>${{ inputs.central-key }}</password>
             </server>
            </servers>
            <activeProfiles>
             <activeProfile>localstack</activeProfile>
            </activeProfiles>
            <profiles>
             <profile>
               <id>localstack</id>
               <properties>
                 <localstack.token>${{ inputs.localstack-token }}</localstack.token>
               </properties>
             </profile>
            </profiles>
          </settings>
        EOF
        # remove this
        cat "$localSettings"

    - name: Import GPG key for Jar signing
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.code-signing-key }}
        passphrase: ${{ inputs.code-signing-passphrase }}
