name: Feature Build
run-name: Build Feature on ${{ github.head_ref || github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types: [ opened, reopened, ready_for_review ]

jobs:
  oss-maven-workflow:
    uses: LimeMojito/oss-maven-standards/.github/workflows/oss-feature-build.yml@master
    secrets: inherit
    permissions:
      contents: write
      packages: read
      id-token: write
