# This workflow runs the standard feature build process for OSS Maven projects.
# It is designed to be delegated to from other repositories or triggered by common events.

name: Feature Build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types: [ opened, reopened, ready_for_review, synchronize ]

jobs:
  oss-maven-workflow:
    uses: LimeMojito/oss-maven-standards/.github/workflows/oss-feature-build.yml@master
    secrets: inherit
    permissions:
      contents: write
      packages: read
      id-token: write
