name: OSS Maven Standards Versions Update

on:
  workflow_dispatch:
  schedule:
    - cron: "25 17 * * 1"
    # at 5:25PM GMT or 3:25AM (+1) AEST on a Monday


jobs:
  version-update:
    uses: ./.github/workflows/oss-maven-patch-version.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      pull-requests: write
