name: OSS Maven Standards Merge Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types:
      - ready_for_review
      - assigned

jobs:
  oss-maven-workflow:
    uses: ./.github/workflows/oss-java-build.yml
    secrets: inherit
