name: OSS Maven Standards Merge Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  oss-maven-workflow:
    uses: ./.github/workflows/oss-java-build.yml
    secrets: inherit
