# This workflow updates Maven project versions.
# It is designed to be delegated to from other repositories or triggered by common events.

name: Lime OSS Update Maven Versions

on:
  workflow_call:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lime Setup Git (Code Agent)
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup-git@master
        with:
          git-access-key: ${{ secrets.LIME_CODE_AGENT_GIT_KEY  }}
          git-signing-key: ${{ secrets.LIME_CODE_AGENT_GIT_SIGNING_KEY }}
          git-id-name: "Lime Code Agent"
          git-id-email: "developers@limemojito.com"

      - name: Environment Setup
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup-java@master
        with:
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}
          central-id: ${{ secrets.LIME_CENTRAL_ID}}
          central-key: ${{ secrets.LIME_CENTRAL_KEY }}
          localstack-token: ${{ secrets.LIME_LOCALSTACK_TOKEN }}

      - name: Update Versions
        id: update_versions
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-version-update@master

      - name: Push any changes
        if: steps.update_versions.outputs.has_changes == 'true'
        shell: bash
        run: |
          echo "Pushing changes to calling branch."
          git push
