# This workflow performs a release build for OSS Maven projects.
# It is designed to be delegated to from other repositories or triggered by common events.

name: OSS Maven Standards Release Build

on:
  workflow_call:

concurrency:
  # this stops release and java build running on the same repo as we have one AWS account involved.
  group: ${{ github.repository }}

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    if: github.actor != 'Lime-Build-Agent'

    # 13/04/2025 Localstack does not like the github ARM runners, reverting to X86
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Lime Setup Git
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup-git@master
        with:
          git-access-key: ${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}
          git-signing-key: ${{ secrets.LIME_BUILD_AGENT_GIT_SIGNING_KEY }}
          git-id-email: "build@limemojito.com"
          git-id-name: "Lime Build Agent"

      - name: Check source changes
        id: changed
        uses: LimeMojito/oss-maven-standards/.github/actions/check-changes-in-source@master

      - name: Lime Setup Java
        if: steps.changed.outputs.changed == 'true'
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup-java@master
        with:
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}
          central-id: ${{ secrets.LIME_CENTRAL_ID}}
          central-key: ${{ secrets.LIME_CENTRAL_KEY }}
          localstack-token: ${{ secrets.LIME_LOCALSTACK_TOKEN }}
          git-access-id: 'Lime-Build-Agent'
          git-access-key: ${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}

      - name: Lime Setup AWS
        if: steps.changed.outputs.changed == 'true'
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup-aws@master
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}

      - name: Lime Setup Docker
        if: steps.changed.outputs.changed == 'true'
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup-docker@master

      - name: Update Library Versions
        if: steps.changed.outputs.changed == 'true'
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-version-update@master

      - name: Maven Release Build
        id: maven-release-build
        if: steps.changed.outputs.changed == 'true'
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-release@master
        with:
          code-signing-key-name: Lime Mojito Pty Ltd
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}

      - name: Update Changelog
        if: steps.changed.outputs.changed == 'true'
        uses: LimeMojito/oss-maven-standards/.github/actions/update-changelog@master
        timeout-minutes: 8
        with:
          agent-token: ${{ secrets.LIME_CODE_AGENT_JUNIE_TOKEN }}
          github-token: ${{ secrets.LIME_CODE_AGENT_GITHUB_TOKEN }}

      - name: Push source changes to default branch and release tag.
        if: steps.changed.outputs.changed == 'true'
        run: |
          git push origin --quiet
          git push origin --quiet tag ${{steps.git_release_version.outputs.build-version}}

      - name: Version ${{ steps.maven-release-build.outputs.release-version }}
        if: steps.changed.outputs.changed == 'true'
        shell: bash
        run: |
          echo "Release Version: ${{ steps.maven-release-build.outputs.release-version }}"
