name: OSS Release Build

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Environment Setup
        uses: ./.github/actions/lime-env-setup
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}

      - name: Import GPG key for Version Update
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.LIME_BUILD_AGENT_GIT_SIGNING_KEY }}
          git_committer_email: "build@limemojito.com"
          git_committer_name: "Lime Build Agent"
          git_user_signingkey: true
          git_push_gpgsign: false
          git_tag_gpgsign: true
          git_commit_gpgsign: true
          git_config_global: true

      - name: Configure OSSRH Credentials
        shell: bash
        run: |
          touch local-settings.xml 
          echo '<?xml version="1.0" encoding="UTF-8"?>' >> local-mvn-settings.xml
          echo '<settings>' >> local-mvn-settings.xml
          echo '<servers>' >> local-mvn-settings.xml
          echo '<server>' >> local-mvn-settings.xml
          echo '<id>server.id</id>' >> local-mvn-settings.xml
          echo '<username>${{ secrets.LIME_OSSRH_ID }}</username>' >> local-mvn-settings.xml
          echo '<password>${{ secrets.LIME_OSSRH_KEY }}</password>' >> local-mvn-settings.xml
          echo '</server>' >> local-mvn-settings.xml
          echo '</servers>' >> local-mvn-settings.xml
          echo '</settings>' >> local-mvn-settings.xml

      - name: Prepare Release Build with Maven
        id: git_setup
        shell: bash
        run: |
          mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          KEY_PATH=$PWD/git-commit-key
          echo '${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}' > $KEY_PATH
          chmod 600 $KEY_PATH
          
          git config core.sshCommand "ssh -i $KEY_PATH"
          remote_url="$(git config --get remote.origin.url)"
          url="$(echo $remote_url | sed -r 's/https:\/\/github.com\/([^/]+)/git@github.com:\1/').git"  
          echo "Switched origin from $remote_url to $url"
          git remote set-url origin "$url"
          
          git add .
          git commit -S -m "[Release] updated version in pom.xml"
          git push
          rm $KEY_PATH
          echo "lime-scm-url=scm:git:${url}" >> "$GITHUB_OUTPUT"

      - name: Perform Release Build with Maven
        shell: bash
        run: mvn -B --settings local-mvn-settings.xml -DconnectionUrl="${steps.git_setup.outputs.lime-scm-url}" -Dgpg.keyname='Lime Mojito Pty Ltd' release:perform

      - name: Remove Credentials
        shell: bash
        run: |
          rm -f local-mvn-settings.xml 
          rm -f git-commit-key
