name: OSS Release Build

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Environment Setup
        uses: ./.github/actions/lime-env-setup
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          ssh-private-key: ${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}
          git-release-bot-name: "Lime-Build-Agent"
          git-release-bot-email: "build@limemojito.com"
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.LIME_BUILD_AGENT_SIGNING_KEY_ID }}
          gpg-key: ${{ secrets.LIME_BUILD_AGENT_SIGNING_KEY_BASE64 }}
          maven-servers: ${{ secrets.MVN_OSSRH_REPOSITORY }}
