# This workflow performs a release build for OSS Maven projects.
# It is designed to be delegated to from other repositories or triggered by common events.

name: OSS Release Build

on:
  workflow_call:

concurrency:
  # this stops release and java build running on the same repo as we have one AWS account involved.
  group: ${{ github.repository }}

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    if: github.actor != 'Lime-Build-Agent'

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Environment Setup
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup@master
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}
          git-access-key: ${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}
          git-signing-key: ${{ secrets.LIME_BUILD_AGENT_GIT_SIGNING_KEY }}
          central-id: ${{ secrets.LIME_CENTRAL_ID}}
          central-key: ${{ secrets.LIME_CENTRAL_KEY }}
          localstack-token: ${{ secrets.LIME_LOCALSTACK_TOKEN }}

      - name: Update Versions
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-version-update@master

      - name: Update Documentation
        uses: LimeMojito/oss-maven-standards/.github/actions/invoke-agent@master
        with:
          agent-token: ${{ secrets.LIME_CODE_AGENT_JUNIE_TOKEN }}
          prompt: |
            Using the version number from pom.xml minus -SNAPSHOT, update CHANGELOG.md to summarize the git commits since 
            the last release tag, where the last release tag is the top most heading of changes in the current 
            CHANGELOG.md.
            
            In the summary that has been added perform the following;
              - where there are multiple summary items containing related issues keys (#XXXXX or AAA-XXX format) group 
                these items and summarize into one description of the changes per issue.
              - where there are multiple summary items referring to version updates or pom updates, replace them with a 
                single item that is "Updated versions and security patches."
              - remove all summary items that contain any of the following
                - [maven-release-plugin]
                - [Release]
                - [Development]
                - [artifactory-release]
                - updating poms
              - Remove any summary items that refer to merges.
            
            Add a heading of Latest Changes with content as a link to the CHANGELOG.md in the Readme.md file if it 
            doesn't already exist.

            Do not commit these changes or make a pull request, leave the files edited in the version control workspace.

      - name: Commit Documentation updates
        shell: bash
        run: |
          echo "Committing Documentation updates."
          git add .
          git commit -S -m "Updated Documentation for release build."

      - name: Maven Release Build
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-release@master
        with:
          code-signing-key-name: Lime Mojito Pty Ltd
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}
