# This workflow performs a feature build for OSS Maven projects.
# It is designed to be delegated to from other repositories or triggered by common events.

name: OSS Maven Standards Feature Build

on:
  workflow_call:

concurrency:
  # this stops release and java build running on the same repo as we have one AWS account involved.
  group: ${{ github.repository }}

permissions:
  id-token: write
  contents: write

jobs:
  build:
    if: github.actor != 'Lime-Build-Agent'

    runs-on: ubuntu-24.04-arm

    steps:
      - name: Environment Setup
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup@master
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}
          git-access-key: ${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}
          git-signing-key: ${{ secrets.LIME_BUILD_AGENT_GIT_SIGNING_KEY }}
          central-id: ${{ secrets.LIME_CENTRAL_ID}}
          central-key: ${{ secrets.LIME_CENTRAL_KEY }}
          localstack-token: ${{ secrets.LIME_LOCALSTACK_TOKEN }}

      - name: Update Versions
        id: update_versions
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-version-update@master

      - name: Current Version
        id: current_version
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-version-number@master

      - name: Build with Maven
        id: build
        # install is required for the framework as CDK is trying to load the current library in another process.
        run: |
          export MAVEN_GPG_PASSPHRASE="${{ secrets.LIME_SIGNING_PASSPHRASE }}"
          mvn -B --color always --no-transfer-progress --file pom.xml -Dbuild.number=${{github.run_number}} -Dgpg.keyname='Lime Mojito Pty Ltd' install

      - name: Upload Docker logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: docker-logs
          path: ${{ github.workspace }}/**/target/docker-logs/*
          retention-days: 1
          compression-level: 9

      - name: Push any changes
        if: steps.update_versions.outputs.has_changes == 'true'
        shell: bash
        run: |
          echo "Pushing changes to calling branch."
          BRANCH=$(git branch --show-current) && [ -n "$BRANCH" ] && git push

      - name: Version ${{steps.current_version.outputs.maven-version-number}}
        shell: bash
        run: |
          echo -e "\n\nFeature Build ${{steps.current_version.outputs.maven-version-number}} build ${{ github.run_number }}"
