name: OSS Java Build

on:
  workflow_call:

concurrency:
  # this should stop release and java build running on the same repo as we have one AWS account involved.
  group: ${{ github.repository }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Environment Setup
        uses: ./.github/actions/lime-env-setup
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}

      - name: Build with Maven
        # Release profile to check javadoc, signing, etc.
        # install is required for framework as CDK is trying to load current library in another process.
        run: mvn -B -Dstyle.color=always --file pom.xml -Prelease -Dbuild.number=${{github.run_number}} -Dgpg.keyname='Lime Mojito Pty Ltd' install
