name: OSS Release Build

on:
  workflow_call:

concurrency:
  # this should stop release and java build running on the same repo as we have one AWS account involved.
  group: ${{ github.repository }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Environment Setup
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup@master
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}

      - name: Configure OSSRH Credentials
        id: maven_setup
        shell: bash
        run: |
          localSettings=~/.m2/settings.xml 
          echo '<?xml version="1.0" encoding="UTF-8"?>' > $localSettings
          echo '<settings>' >> $localSettings
          echo '<servers>' >> $localSettings
          echo '<server>' >> $localSettings
          echo '<id>central</id>' >> $localSettings
          echo '<username>${{ secrets.LIME_CENTRAL_ID }}</username>' >> $localSettings
          echo '<password>${{ secrets.LIME_CENTRAL_KEY }}</password>' >> $localSettings
          echo '</server>' >> $localSettings
          echo '</servers>' >> $localSettings
          echo '</settings>' >> $localSettings

      - uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}"

      - name: Maven Release Build
        uses: LimeMojito/oss-maven-standards/.github/actions/maven-release@master
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}
          code-signing-key-name: Lime Mojito Pty Ltd
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}
          git-access-key: ${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}
          git-signing-key: ${{ secrets.LIME_BUILD_AGENT_GIT_SIGNING_KEY }}
