name: OSS Java Build

on:
  workflow_call:

concurrency:
  # this should stop release and java build running on the same repo as we have one AWS account involved.
  group: ${{ github.repository }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Environment Setup
        uses: LimeMojito/oss-maven-standards/.github/actions/lime-env-setup@master
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          code-signing-key: ${{ secrets.LIME_SIGNING_KEY }}
          code-signing-passphrase: ${{ secrets.LIME_SIGNING_PASSPHRASE }}

      - uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.LIME_BUILD_AGENT_GIT_KEY }}"

      - name: Build with Maven
        # install is required for framework as CDK is trying to load current library in another process.
        run: |
          export MAVEN_GPG_PASSPHRASE="${{ secrets.LIME_SIGNING_PASSPHRASE }}"
          mvn -B -Dstyle.color=always --file pom.xml -Dbuild.number=${{github.run_number}} -Dgpg.keyname='Lime Mojito Pty Ltd' install
