name: OSS Release Build

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Environment Setup
        uses: ./.github/actions/lime-env-setup
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          signing-key: ${{ secrets.LIME_SIGNING_KEY }}

      - name: Configure Release Git User
        shell: bash
        run: |
          git config user.email "build@limemojito.com"
          git config user.name "Lime-Build-Agent"

      - name: Configure OSSRH Credentials
        shell: bash
        run: |
          touch .maven_settings.xml 
          echo aws_host="$AWS_HOST" >> .maven_settings.xml
          echo '<settings>' >> .maven_settings.xml
            echo '<servers>' >> .maven_settings.xml
            echo '<server>' >> .maven_settings.xml
            echo '<id>server.id</id>' >> .maven_settings.xml
            echo '<username>${{ secrets.LIME_OSSRH_ID }}</username>' >> .maven_settings.xml
            echo '<password>${{ secrets.LIME_OSSRH_KEY }}</password>' >> .maven_settings.xml
            echo '</server>' >> .maven_settings.xml
            echo '</servers>' >> .maven_settings.xml
            echo '</settings>' >> .maven_settings.xml

      - name: Release Build with Maven
        # Release profile to check javadoc, signing, etc.
        run: mvn -B --file pom.xml -Dgpg.keyname='Lime Mojito Pty Ltd' release:prepare release:perform release:clean

      - name: Remove OSSRH Credentials
        shell: bash
        run: |
          rm -f .maven_settings.xml 
