name: OSS Release Build

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Environment Setup
        uses: ./.github/actions/lime-env-setup
        with:
          aws-region: ${{ secrets.LIME_AWS_REGION }}
          role-to-assume: ${{ secrets.LIME_AWS_ROLE_ARN }}
          signing-key: ${{ secrets.LIME_SIGNING_KEY }}

      - name: Release Build with Maven
        # Release profile to check javadoc, signing, etc.
        # install is required for framework as CDK is trying to load current library in another process.
        run: mvn -B --file pom.xml -Dgpg.keyname='Lime Mojito Pty Ltd' -DpreparationGoals=clean release:prepare release:perform
