name: OSS Maven Standards Release Build

on:
  workflow_dispatch

jobs:
  oss-release-workflow:
    uses: ./.github/workflows/oss-release-build.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: write
