name: OSS Maven Standards Release Build

on:
  push:
    branches:
      - main
      - master

jobs:
  oss-release-workflow:
    uses: ./.github/workflows/oss-release-build.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
